version: '3.6'
services:
  node:
    container_name: Back-SocialCosplay
    image: 'node:latest'
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    command:
      - /bin/sh
      - '-c'
      - 'npm install && npm run start-dev'
    links:
      - mongo
    ports:
      - '7000:7000'
    volumes:
      - './:/home/node/app'
    networks:
      - API_Networks
  mongo:
    container_name: db-SocialCosplay
    image: 'mongo:4.0.7'
    ports:
      - '27017:27017'
    networks:
      - API_Networks
networks:
  API_Networks:
    driver: bridge
