version: '3.6'
services:
  node:
    container_name: Back-SocialCosplay
    build: .
    command:
      - /bin/sh
      - '-c'
      - 'npm run start-dev'
    links:
      - mongo
    ports:
      - '7000:7000'
    volumes:
      - './:/home/app'
      - '/home/app/node_modules'
    networks:
      - API_Networks
  mongo:
    container_name: dbsocial
    image: 'mongo'
    ports:
      - '27017:27017'
    networks:
      - API_Networks

networks:
  API_Networks:
    driver: bridge