name: Continuous Integration
on:
  push:
    branches:
      - develop
      - feature/.*
  pull_request:
    branches:
      - master
      - develop

jobs:
  unit_test:
    name: Unit test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: install dependance
        run: npm install
      - name: run unit test
        run: npm run unit_test

  build:
    name : build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: build image
        run: docker build . --file ../../Dockerfile  --tag api_social

  integ_tests:
    name : run integration tests
    runs-on: ubuntu-18.04
    needs: Build
    services:
      dbsocial:
        image: mongo
        ports:
          - 27017:27017
      node:
        image: .
    steps:
      - uses: actions/checkout@v2
      - name: Integ tests
        run:  docker run --network=backsocialcosplay_API_Networks api_social npm run test